url: 'https://https://susancoort.github.io/NUTRIOMEworkshop1.github.io/'
baseurl: '/NUTRIOMEworkshop1.github.io'

theme: jekyll-theme-cayman
logo_url: 'https://NUTRIOMEworkshop1.github.io/images/nutriome.png'
